### ISSUE TITLE
來源可能是盜版的開源字型，授權沒問題嗎？

### ISSUE THREAD

**Issue by ButTaiwan** [l10n-tw/cwtex-q-fonts#15]
cwTex 開源字型系列在網路上流傳已久。
但明體顯然是掃描寫研（照像排版）的繁體字打樣，而黑體、仿宋顯然是掃描修改自文鼎的字樣。
建立在這樣背景的開源字型，沒有問題嗎？

PS. Google Fonts方面接到抗議，已經把cwTex系列字型全數下架了。

PS. 不知原始作者是否能舉證字樣為自己所畫或得到授權？

**Comment by chenpanliao** [comment]
到目前為止，我尚未在開源界看到任何明確消息。吳教授的cwtex系統也仍持續更新著。我並沒有預設立場，也歡迎提出任何相關訊息。若侵權證據充足則自然應考慮停止散布。

若想聯絡最原始的作者，請向吳教授請教。本專案並不由他負責。

**Comment by ButTaiwan** [comment]
上面第一排是日本照相排版公司寫研80年代在台灣販售的「本蘭明體L」照相排版字型。（來自繁體中文版型錄）
第二排是cwTex明體 (橫向放大5%左右)，幾乎是完全吻合。（第三排是兩者相疊的結果）

可推測cwTex明體的來源並不是 Tsong-Min Wu 及 Tsong-Huey Wu 等人從製圖開始設計，
而是單純掃描「本蘭明體L」後 auto-trace 數位化的結果。

![image](https://user-images.githubusercontent.com/5418570/56078134-220c4900-5e17-11e9-9544-a523c2bb04b8.png)

**Comment by KrasnayaPloshchad** [comment]
若侵權問題得到證實，不妨用台大中明體重製，再重新散布。

**Comment by KrasnayaPloshchad** [comment]
近來發現有[台大中明體](https://www.ibiblio.org/pub/packages/ccic/software/fonts/big5/ms-win/ctlg.html)與[文鼎PL明體U20-L](https://web.archive.org/web/20131122235603/http://www.arphic.com/tw/news/2010/20100420.html)兩個資源。一旦侵權問題得到查證，哪一個可以用來取代原有字形？

**Comment by zerng07** [comment]
> 近來發現有[台大中明體](https://www.ibiblio.org/pub/packages/ccic/software/fonts/big5/ms-win/ctlg.html)與[文鼎PL明體U20-L](https://web.archive.org/web/20131122235603/http://www.arphic.com/tw/news/2010/20100420.html)兩個資源。一旦侵權問題得到查證，哪一個可以用來取代原有字形？

兩者僅非商業免費使用，皆不是自由或開源字型。

另外，臺灣的著作權法不保障字形的外觀設計，只保護著作的表達形式（字型檔、字庫、軟體、程式），而詳細情形則根據法律解讀不同有不同看法。此 Issue 不在專案可解決範圍之內，先關閉；如果有明確法律定論還請提出，屆時再開新的 Issue。

**Comment by hugolpz** [comment]
Has this issue been assessed and fixed, by using alternative way to generate the MingTi font ? MakeMeAHanzi (or AnimCJK?) project has drawn the _strokes middle line_ of 7000+ characters. From those middle lines and ~100 basic strokes it is possible to generate truly free MingTi. 

@Parsimonhi, could you point us to the exact source for middle lines ?

## See also
* https://github.com/skishore/makemeahanzi
* https://github.com/parsimonhi/animCJK
* https://en.wikipedia.org/wiki/List_of_CJK_fonts

**Comment by parsimonhi** [comment]
@hugolpz: to generate the "middle line", i used two ways.
1) inkscape (in this case, i made the line one by one)
2) assuming one already has a svg of each character with each stroke stored in a different path, AND one has the starting point of the "middle line" of each stroke (it can be approximative), it is possible to use a script to generate automatically all the "middle line". I did such a script adapted for the Arphic fonts, but didn't publish it: no time to make a version of the script clean enough for publishing.

**Comment by hugolpz** [comment]
To the cwtex team : the noto project provides open source font for mingti and heiti. You could use them to discard current font file with potential copyright dispute, and instead use an edited version of Noto font files.
* _Noto Serif_ (mingti) 
* _Noto Sans_ (heiti)

Ex:
* File: NotoSerifTC-Medium.otf   (Traditional Chinese glyphs)
* URL: [fonts.google.com/specimen/Noto+Serif+TC](https://fonts.google.com/specimen/Noto+Serif+TC?preview.text=亠人亻儿斉齐齒齿龍龙龜龟龠&preview.text_type=custom)
* License: Open Font License.

PS @parsimohi: Une précision que j'ai oublié de mentionner... cwTeX est une des rares series de fonts open source, mais la discussion en chinois ci-dessus ouvre la possibilité que la police cwTeX mingti soit en fait dérivée d'une police copyrighté. Je les encourageait à utiliser MakeMeAHanzi pour recreer une font mingti 100% open source. Mais Noto existe sous Open Font License, autant l'utiliser.

**Comment by zerng07** [comment]
The fonts of cwtex typesetting system are work from Tsong-Min Wu and Tsong-Huey Wu, later transformed into TTF files by Edward G.J. Lee with the permission from authors.

According to the investigation above by ButKo, cwtex Ming might be created from autotracing the "本蘭明體L font catalog" while cwtexHei and cwtexFangsong might be created from the same method form Arphic (文鼎) work.

Using autotracing scripts to create new fonts is still debatable in legal area and out of the scope of cwtex-q-fonts project.
The original goal of this project is served as an archive and maintain them with minimal changes, only small fixes are added.

Thus, for people who want to derive work from cwtex-q-fonts, we suggested using Noto Serif for mingti and Noto Sans for heiti directly instead of the fonts in this project. It is advised to use cwTeXQKai and cwTeXQYuan only to avoid possible legal risks (although there are no arguments provided yet until today, but we are not sure).  

Maybe it is better for us to add some warning sentences in the project home page? @chenpanliao

**Comment by hugolpz** [comment]
Oh I see. So cwTeX creator use the : 
* PD-font clause : font's vector data is copyrighted, raster shapes are not
* PD-ancient-script clause: ancient styles are not copyrighted.

So from fonts and theirs raster scans, they created _"original vector data"_... representing centuries years old Public Domain shapes:

* Mingti shapes are 400~1000+ years old. There is no much creativity involved.
* Kaishu 2000+.
* Heiti ?

Etc. Interesting.

### See also
These are used on Wikipedia and Commons Wikimedia and legally valid in the USA at least.
![Screenshot_2021-04-21_00-14-39](https://user-images.githubusercontent.com/1420189/115470698-01153480-a237-11eb-98fb-fd0a4044542d.png)
![Screenshot_2021-04-21_00-15-41](https://user-images.githubusercontent.com/1420189/115470695-ffe40780-a236-11eb-96d1-be1a61491028.png)

## Noto
Still, since there is still a lack of legal clarity it could be better to visibly recommend _Noto Serif_ and _Noto Sans_, so no users are mislead into believing cwtex is 100% open source, then put themselves at risk.

**Comment by chenpanliao** [comment]
> 
> 
> The fonts of cwtex typesetting system are work from Tsong-Min Wu and Tsong-Huey Wu, later transformed into TTF files by Edward G.J. Lee with the permission from authors.
> 
> According to the investigation above by ButKo, cwtex Ming might be created from autotracing the "本蘭明體L font catalog" while cwtexHei and cwtexFangsong might be created from the same method form Arphic (文鼎) work.
> 
> Using autotracing scripts to create new fonts is still debatable in legal area and out of the scope of cwtex-q-fonts project.
> The original goal of this project is served as an archive and maintain them with minimal changes, only small fixes are added.
> 
> Thus, for people who want to derive work from cwtex-q-fonts, we suggested using Noto Serif for mingti and Noto Sans for heiti directly instead of the fonts in this project. It is advised to use cwTeXQKai and cwTeXQYuan only to avoid possible legal risks (although there are no arguments provided yet until today, but we are not sure).
> 
> Maybe it is better for us to add some warning sentences in the project home page? @chenpanliao

No problem. Add a subsection "版權爭議" in README.md
